CREATE OR REPLACE TRIGGER ADDINDEXCUSTOMER
AFTER INSERT ON CUSTOMER
REFERENCING new AS newRow
  BEGIN
    UPDATE INCREMENTS
    SET INCREMENTS=INCREMENTS+1
    WHERE
      TABLE_NAME='customer' AND COLUMN_NAME='id'
    ;
  END;