INSERT INTO DATABASE.CUSTOMER (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (16, '백지영', '여', '82041', '충남');
INSERT INTO DATABASE.CUSTOMER (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (17, '신승훈', '남', '82064', '제주');
INSERT INTO DATABASE.CUSTOMER (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (18, '김진표', '남', '82063', '전북');
INSERT INTO DATABASE.CUSTOMER (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (14, '길', '남', '8202', '서울');
INSERT INTO DATABASE.CUSTOMER (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (15, '강타', '남', '82031', '경기');