INSERT INTO DATABASE.STAFF (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (14, '보아', '여', '강원', '82033');
INSERT INTO DATABASE.STAFF (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (15, '유재석', '남', '부산', '82051');
INSERT INTO DATABASE.STAFF (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (16, '강개리', '남', '대구', '82053');
INSERT INTO DATABASE.STAFF (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (12, '박진영', '남', '경북', '82054');
INSERT INTO DATABASE.STAFF (ID, NAME, GENDER, ADDRESS, PHONE) VALUES (13, '양현석', '남', '울산', '82052');